### ISSUE TITLE
can we start salesiq sdk from two different packages or two different android projects . If yes , how ?

### ISSUE THREAD

**Issue by rohitlien** [zoho/salesiq-sdk-android-sample#3]

**Comment by Angu-G** [comment]
@rohitlien Yes you can do so.
One website can hold one SDK at a time. You can create another website if you want to integrate another SDK. 
Thank you !!

**Comment by Angu-G** [comment]
Yes you can do so by [creating more websites](https://www.zoho.com/salesiq/help/how-to-create-websites.html) in the SalesIQ portal since each website can hold one package (or) project at a time.

**Comment by Angu-G** [comment]
@rohitlien , Yes you can do so by [creating more websites](https://www.zoho.com/salesiq/help/how-to-create-websites.html) in the SalesIQ portal since each website can hold one package (or) project at a time.
