### ISSUE TITLE
how to hide zoho salesiq android when loading with login facebook

### ISSUE THREAD

**Issue by stnwj** [zoho/salesiq-sdk-android-sample#4]
this result:
![101893517_577495366537414_1321079266770681856_n](https://user-images.githubusercontent.com/43704613/83835151-3cd80600-a71a-11ea-8c96-968dfb7eb0e0.png)

this code when hide in activitylogin
![image](https://user-images.githubusercontent.com/43704613/83835312-a5bf7e00-a71a-11ea-98b3-54b73cbbd450.png)

this code when login fb:
![image](https://user-images.githubusercontent.com/43704613/83835268-8cb6cd00-a71a-11ea-9c0e-1b1a377379aa.png)

**Comment by Angu-G** [comment]
Hello @stnwj  ,
        The API you have used is activity specific ie., the chat bubble will be shown or hidden only in the specific activity from where ZohoSalesIQ.Chat.setVisibility(MbedableComponent.CHAT,false) is called. So please make sure that it is called from loading activity.
       Also we have an API to show/hide chat bubble throughout your application.
            **ZohoSalesIQ.Chat.setFloatingChatButtonVisibility(true/false);**
       You can call this API with **false** param upon your loading screen and **true** param from where you want to show the chat bubble.

**Comment by stnwj** [comment]
t

> Hello @stnwj ,
> The API you have used is activity specific ie., the chat bubble will be shown or hidden only in the specific activity from where ZohoSalesIQ.Chat.setVisibility(MbedableComponent.CHAT,false) is called. So please make sure that it is called from loading activity.
> Also we have an API to show/hide chat bubble throughout your application.
> **ZohoSalesIQ.Chat.setFloatingChatButtonVisibility(true/false);** [api link](https://www.zoho.com/salesiq/help/developer-section/android-sdk-launcher-button.html)
> You can call this API with **false** param upon your loading screen and **true** param from where you want to show the chat bubble.

thx you. it's work
